<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.automation.UIAutomation.Homepage.TC001_VerifyLoginwithInvalidCredentials" tests="1" time="2.948" ignored="0" failures="1" timestamp="22 Sep 2017 15:45:53 GMT" skipped="0" hostname="DESKTOP-59JL777" errors="0">
  <testcase name="verifyLoginWithInvalidCredentials" time="2.948" classname="com.test.automation.UIAutomation.Homepage.TC001_VerifyLoginwithInvalidCredentials">
    <failure type="junit.framework.ComparisonFailure" message="expected:&lt;Authentication [failed.]&gt; but was:&lt;Authentication [Failed]&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Authentication [failed.]> but was:<Authentication [Failed]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.test.automation.UIAutomation.Homepage.TC001_VerifyLoginwithInvalidCredentials.verifyLoginWithInvalidCredentials(TC001_VerifyLoginwithInvalidCredentials.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
</testsuite> <!-- com.test.automation.UIAutomation.Homepage.TC001_VerifyLoginwithInvalidCredentials -->
